### PR TITLE
minor changes to code, removed redundant code

### PR DESCRIPTION
**Pull request by LukaGitH**

### CODE REVIEW

**Comment by LukaGitH** [comment]
Did you see that? I measured BME only and it went to 0.1uA as per datasheet when there was no measurement in progress. I guess I should measure whole moteino + BME, since I don't have weather shield as you do. 
Just don't see, why there would be any higher consumption if BME does what it needs.

**Comment by LowPowerLab** [comment]
I actually measured a whole unit (moteino+WS). Without the MODE_SLEEP after measurements, it uses 0.4mA. So I needed to add setMode(MODE_SLEEP) after each reading/measurement to ensure it sleeps and the whole mote goes to less than 10uA in watchdog mode.

**Comment by LukaGitH** [comment]
I started with code that is for weatherNode, unchanged.  Moteino(no flash) + BME ends up on ~8uA
Then I comment out two `bme280.setMode(MODE_SLEEP);` and I get the same 8uA, as expected.
I think code is fine without `bme280.setMode(MODE_SLEEP);`

PM on forum, let's find what is different

**Comment by LukaGitH** [comment]
Code will work without `bme280.setMode(MODE_SLEEP);`, but end user might not know that, so code will stay as  TAKE MEASUREMENT > read > SLEEP

**Comment by LowPowerLab** [comment]
Ok I made the GATEWAY ID change, the rest I left explicit to avoid confusion.

**Pull request closed without merging**
