### PR TITLE
Fixed network hang in sendACK and some other improvements

### PR DESCRIPTION
**Pull request by martiera**
Improvements after noticed hanged network:
- fixed sendACK
- fixed millis() datatype, transmit timeout and malformed payload (by Jeremy Gilbert suggestions, see https://github.com/jgilbert20/RFM69)

Details see https://lowpowerlab.com/forum/index.php/topic,736.30.html

### CODE REVIEW

**Comment by JojoS62** [comment]
thanks, this fix works for me too. Why is not yet merged? Without this, the received SENDERID and TARGETID are overwritten with zero by the sendACK.

**Comment by LowPowerLab** [comment]
This was already merged manually.

**Comment by JojoS62** [comment]
I'm still testing the sendACK() without calling receiveDone. In about 90% I get a rssi level < -100 dB and canSend is true and ACK is sent. But sometimes the level does not go below -40 dB until timeout (already increased to 100 ms). Strange thing is that the -40 dB is also the usual rx level for my test setup. I don't think there is another transmitter disturbing. Is it possible that I read the rssi level too fast?

**Comment by LowPowerLab** [comment]
Hard to say what's going on. I suggest the forums for discussion.
receiveDone puts the radio in RX mode. sendACK sends an empty packet with ACK bit set to the last sender. So you have to do things in the right order. The examples in this lib illustrate this approach.

**Pull request closed without merging**
