### PR TITLE
Update version to 1.4.0

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by ivankravets** [comment]
Thanks for the merge! I see that 1.4.0 branch contains `library.json` manifest without a version field. Is it possible to bump version to 1.4.1 (create a tag as well) and update `library.json` "version" field to 1.4.1? It's not urgent. This step will trigger our registry to update library.

**Comment by LowPowerLab** [comment]
Ok so this means we make another update to library.json version field to "1.4.1" and then create a tag?

**Comment by ivankravets** [comment]
You are right. Bump "version" in `library.json` and `library.properties` files and create a tag.

**Comment by LowPowerLab** [comment]
Done.

**Comment by ivankravets** [comment]
Thank you so much! 🍺
Now evrything is OK! https://platformio.org/lib/show/92/RFM69

**Comment by LowPowerLab** [comment]
Thanks for your support, it's my pleasure of working with you!

**Pull request merged**
