### PR TITLE
Continuous Integration

### PR DESCRIPTION
**Pull request by ivankravets**
Hi,

Please enable @travis-ci following the steps 1, 2 and 5 here http://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A 

For more details please follow to:

* Official Travis CI Documentation for PlatformIO: https://docs.travis-ci.com/user/integration/platformio/
* PlatformIO documentation for Travis CI: http://docs.platformio.org/en/latest/ci/travis.html

Thanks a lot!

### CODE REVIEW

**Comment by LowPowerLab** [comment]
I added --board=moteinomega but on some sketches it passes, some fail with this. Any suggestions for how I could fix this?
Also not sure why you originally had --board=megaatmega2560 included?

**Comment by ivankravets** [comment]
> I added --board=moteinomega but on some sketches it passes, some fail with this. Any suggestions for how I could fix this?

Please take a look at 3-rd example with `PLATFORMIO_CI_BOARDS_ARGS` http://docs.platformio.org/en/latest/ci/travis.html#examples

> Also not sure why you originally had --board=megaatmega2560 included?

Sorry, I've seen this `Please ensure chosen MCU is either 168, 328P, 32U4 or 2560` and tried to find `2560`-based board.

Please keep me in touch if you need any help with this config for @travis-ci.

**Comment by LowPowerLab** [comment]
Thanks, unfortunately I didn't have much luck.
I reverted to **--board=moteino** only but there is still one sketch failing, could you take a look and see if you have any suggestions: https://travis-ci.org/LowPowerLab/RFM69/jobs/114965530
This compiles OK on my machine with IDE 1.0.6.

**Comment by valeros** [comment]
Hi @LowPowerLab 
Looks like the problem is in `st7036-display-driver` library. I've created a PR with a fix in their repo. I'll notify you as soon as they merge it.
And here is [`.travis.yml`](https://github.com/valeros/RFM69/blob/master/.travis.yml) for your library with `moteinomega`.

**Comment by ivankravets** [comment]
@LowPowerLab We have updated dependent library but it is cached. Please clean cache for the repo

**Comment by LowPowerLab** [comment]
@ivankravets I am still having issues although I have tried many things and I even removed the example sketch which required an external library and always failed CC. Cleaned the caches every time. What am I missing? Why is it still trying to compile that sketch when it's not even there any more (Examples/PiGateway/PiGateway_withLCD.ino) ?
https://travis-ci.org/LowPowerLab/RFM69

**Comment by ivankravets** [comment]
@LowPowerLab the problem is not linked with Travis CI, PlatformIO or even GitHub. You need to remove/disable example from CI process.

See my PR https://github.com/LowPowerLab/RFM69/pull/40

Please sorry for any problems.

**Comment by LowPowerLab** [comment]
I knew I missed something obvious, it's fixed, thanks for the help!

**Comment by ivankravets** [comment]
Thank you too that use PlatformIO.

P.S: You can revert deleted example :blush:

**Comment by LowPowerLab** [comment]
I already did! :blush:
I was wondering if in the future the error messaging on the CC could be more indicative that an example is missing...just a proposal.

**Comment by ivankravets** [comment]
Thanks! I'll think on it.

https://travis-ci.org/LowPowerLab/RFM69/jobs/119411269

> Error: Nothing to build. Please put your source code files to '/tmp/tmpal91LD/src' folder
It really sounds messy :(


> On Mar 30, 2016, at 19:41, Felix Rusu <notifications@github.com> wrote:
> 
> I already did! 
> I was wondering if in the future the error messaging on the CC could be more indicative that an example is missing...just a proposal.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> 

Regards, Ivan Kravets
   - Founder and CTO at PlatformIO.Org
   - Ph.D, Researcher and Software Architect
   - Creativity comes from talent and never from knowledge (c)
________________________
http://www.ikravets.com

**Comment by LowPowerLab** [comment]
Maybe it could be a warning instead of an error, since there is nothing to build the rest of the build should be able to pass, IMO.

**Comment by ivankravets** [comment]
@LowPowerLab please sorry for the late answer. We added this warning to just released PlatformIO 3.0:

- https://community.platformio.org/t/platformio-3-0-the-biggest-update-for-the-years/719/

**Pull request merged**
