### PR TITLE
Arduino101

### PR DESCRIPTION
**Pull request by ingoha**
Compiles for (intel-based) Arduino101:
 * Fixed SPI code
 * Fixed types in RFM_ATC

### CODE REVIEW

**Comment by LowPowerLab** [comment]
Thanks but we need the SPI code for AVR... the conditional blocks would throw that out.

**Comment by ingoha** [comment]
Okay, so I made a mistake(?) The conditional should just block the AVR-specific stuff when compiling on a non-AVR platform. Can the conditional be rewritten to do exactly that?

**Comment by LowPowerLab** [comment]
Probably. I'm guessing you meant to do a **#if not defined (_ARM_)** ?

**Comment by ingoha** [comment]
Just reviewed the patch; the AVR-specific SPI stuff (using internals not present on an intel platform) are in the conditional #if defined (ARM), so it should not affect AVR platforms as the code will be present there. Am I missing something here?

**Comment by LowPowerLab** [comment]
Ok, among other changes, you added the first and last lines of this:
```
+#if defined (__arm__)
    // save current SPI settings
    _SPCR = SPCR;
    _SPSR = SPSR;
 +#endif
```
So, these changes will eliminate the 2nd and 3rd lines (for AVR), when in fact those **_are required_** for AVR. Is that more clear now?

**Comment by ingoha** [comment]
Thank you for your patience...
I still do not understand it, I am afraid; to me those lines cited by you mean:
(only) if we are on an AVR platform,
do AVR-specific stuff (use internal registers only present in AVT µCs)
You seem to understand the logic the other way round.
So my question is: How do I mark lines of code so they are only used on an AVR platform?

**Comment by tlanfer** [comment]
@ingoha Any chance you are confusing ARM and AVR?

**Comment by ingoha** [comment]
Maybe :-)
So should I just replace the conditional with
#if defined(AVR)
???

**Comment by LowPowerLab** [comment]
I think so.
But have you tested this change with real hardware?
Just compiling it is *not* a test :-)

**Comment by ingoha** [comment]
Yep, tested with both atmega328 and Genuino 101

**Comment by LowPowerLab** [comment]
How about this, it's very specific to what the requirements are to include for AVR:
```
#if defined (SPCR) && defined (SPSR)
  // save current SPI settings
  _SPCR = SPCR;
  _SPSR = SPSR;
#endif
```

**Comment by ingoha** [comment]
Thats great :-) Should I update the pull request or will you apply the changes?

**Comment by LowPowerLab** [comment]
I can apply the changes along with a few other things.
Thanks

**Comment by ingoha** [comment]
8-)
And thanks again for your patience.

**Comment by LowPowerLab** [comment]
Done in https://github.com/LowPowerLab/RFM69/commit/c24051e9335185c4431509afbdb4363cbd06e4e6

**Pull request closed without merging**
