### PR TITLE
Updated to new BME280 lib

### PR DESCRIPTION
**Pull request by LukaGitH**
Hello Felix,

I made updates to 3 sketches, moving to updated BME280 lib. from Sparkfun
I tested changes on hardware and it seems, that everything is working. Please take a look

### CODE REVIEW

**Comment by LowPowerLab** [comment]
@ivankravets - do you know why this pull fails?
The referenced Sparkfun_BME280 library (#684) is at v 2.0.1 yet platformio uses v 1.2.0 in the build.

**Comment by ivankravets** [comment]
See 520 line https://travis-ci.org/LowPowerLab/RFM69/jobs/373596409

**Comment by LowPowerLab** [comment]
@ivankravets all works now thanks!!

**Comment by ivankravets** [comment]
Thank you so much that using @PlatformIO!

**Comment by LowPowerLab** [comment]
@LukaGitH thanks for the contribution, I merged and added my tweaks to make sure the BME280 is sleeping when the motes are sleeping.

**Pull request merged**
