### PR TITLE
Support ESP8266 and Hallard RFM69 shield

### PR DESCRIPTION
**Pull request by trizmark**
This PR adds support for ESP8266 coupled with the Hallard RFM69 shield (https://github.com/hallard/WeMos-Lora).

### CODE REVIEW

**Comment by LowPowerLab** [comment]
Sorry but ESP support is already added with different default pins.
Also the ISR_PREFIX is already defined in RFM69.h

**Comment by trizmark** [comment]
Is there a board available with these default pins?

**Comment by LowPowerLab** [comment]
The library supports generic boards and LowPowerLab boards.
Any board can be supported by passing other than default pins through the constructor.

**Comment by trizmark** [comment]
Thank you for taking time to answer my question! I was not aware of the flexibility provided via the constructor.

**Pull request closed without merging**
